from setuptools import setup, find_packages

setup(
    name="mytools",
    version="0.1",
    packages=find_packages(),
    author="Your Name",
    author_email="waajoenglei@gmail.com",
    description="Some useful tools",
    install_requires=[
        "pympler",
        "ijson",
        "ipdb",
        "joblib",
        "nanopq",
        "pynvml",
        "requests",
        "xlrd",
        "xlwt",
        "typing",
        "PyYAML",
        "openai",
        "pillow",
        "numpy",
        "nltk",
        "scipy",
        "spacy",
        "tqdm",
        "pyyaml",
        "sacremoses",
        "datasets",
        "fire",
        "transformers",
        "sentence-transformers",
        "sentencepiece",
        "pytesseract",
        "faiss_gpu==1.7.2",
        "torch",
        "openpyxl"
    ],
)
